apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-job
spec:
  template:
    spec:
      containers:
      - name: pi
        image: 10.100.29.62/kubeflow/train:v3
        resources:
          requests:
            memory: "2G"
        command: ["python3",  "/home/pipeline-demo/train.py"]
      restartPolicy: Never
  backoffLimit: 4